import { afterAll, describe, expect, it } from "bun:test";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";

import { dirname, join } from "pathe";

import { blumeConfigSchema } from "../src/core/schema.ts";
import { migrateStarlight } from "../src/migrate/migrate.ts";
import { mapStarlightConfig } from "../src/migrate/starlight/config.ts";
import {
  rewriteStarlightAsides,
  rewriteStarlightComponents,
  stripStarlightImports,
  unsupportedStarlightComponents,
} from "../src/migrate/starlight/content.ts";
import { normalizeStarlightPageMeta } from "../src/migrate/starlight/frontmatter.ts";
import { starlightI18n } from "../src/migrate/starlight/i18n.ts";

const dirs: string[] = [];

afterAll(async () => {
  await Promise.all(
    dirs.map((dir) => rm(dir, { force: true, recursive: true }))
  );
});

const project = async (files: Record<string, string>): Promise<string> => {
  const root = await mkdtemp(join(tmpdir(), "blume-starlight-"));
  dirs.push(root);
  await Promise.all(
    Object.entries(files).map(async ([rel, content]) => {
      const abs = join(root, rel);
      await mkdir(dirname(abs), { recursive: true });
      await writeFile(abs, content);
    })
  );
  return root;
};

/** Parse the JSON object a generated `blume.config.ts` wraps in `defineConfig`. */
const readGeneratedConfig = (source: string): unknown => {
  const start = source.indexOf("defineConfig(") + "defineConfig(".length;
  const end = source.lastIndexOf(")");
  return JSON.parse(source.slice(start, end));
};

const ASTRO_CONFIG = `import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";

export default defineConfig({
  integrations: [
    starlight({
      title: "My Docs",
      description: "All about my project.",
      social: [
        { icon: "github", label: "GitHub", href: "https://github.com/acme/docs" },
        { icon: "discord", label: "Discord", href: "https://discord.gg/abc" },
      ],
      sidebar: [
        { label: "Start", items: [{ label: "Intro", slug: "guides/intro" }] },
        { label: "Reference", autogenerate: { directory: "reference" } },
      ],
      editLink: { baseUrl: "https://github.com/acme/docs/edit/main/" },
    }),
  ],
});
`;

describe("migrateStarlight config", () => {
  it("translates astro.config starlight() options into blume.config.ts", async () => {
    const root = await project({
      "astro.config.mjs": ASTRO_CONFIG,
      "src/content/docs/index.md": "# Home\n",
    });

    const result = await migrateStarlight(root);
    const config = await readFile(join(root, "blume.config.ts"), "utf-8");

    // Content stays in place under the Starlight collection directory.
    expect(config).toContain('"root": "src/content/docs"');
    expect(config).toContain('"title": "My Docs"');
    expect(config).toContain('"description": "All about my project."');
    // Autogenerated sidebar group maps to a Blume `root` group.
    expect(config).toContain('"root": "reference"');
    expect(config).toContain('"label": "Reference"');
    // Social links land in footer.socials; the github URL also seeds `github`.
    expect(config).toContain('"github": "https://github.com/acme/docs"');
    expect(config).toContain('"discord":');
    expect(config).toContain('"owner": "acme"');
    expect(config).toContain('"repo": "docs"');
    expect(config).toContain('"branch": "main"');
    expect(result.moved).toBe(1);
    // The generated config must satisfy Blume's strict schema as-is.
    expect(
      blumeConfigSchema.safeParse(readGeneratedConfig(config)).success
    ).toBe(true);
  });

  it("writes a config and warns when src/content/docs is missing", async () => {
    const root = await project({ "astro.config.mjs": ASTRO_CONFIG });
    const result = await migrateStarlight(root);
    const config = await readFile(join(root, "blume.config.ts"), "utf-8");

    expect(config).toContain('"title": "My Docs"');
    expect(result.moved).toBe(0);
    expect(result.warnings.some((w) => w.includes("not found"))).toBe(true);
  });

  it("falls back to a default config when no astro.config exists", async () => {
    const root = await project({ "src/content/docs/index.md": "# Home\n" });
    const result = await migrateStarlight(root);
    const config = await readFile(join(root, "blume.config.ts"), "utf-8");

    expect(config).toContain('"title": "Documentation"');
    expect(result.warnings.some((w) => w.includes("astro.config"))).toBe(true);
  });
});

describe("migrateStarlight content", () => {
  it("rewrites asides, strips imports, and maps frontmatter in place", async () => {
    const root = await project({
      "astro.config.mjs": ASTRO_CONFIG,
      "src/content/docs/guides/intro.mdx": `---
title: Intro
pagefind: false
sidebar:
  badge:
    text: New
    variant: success
template: splash
---
import { Aside, TabItem, Tabs } from "@astrojs/starlight/components";

<Aside type="caution" title="Heads up">Be careful.</Aside>

<Tabs>
  <TabItem label="npm">install</TabItem>
</Tabs>
`,
    });

    await migrateStarlight(root);
    const page = await readFile(
      join(root, "src/content/docs/guides/intro.mdx"),
      "utf-8"
    );

    expect(page).not.toContain("@astrojs/starlight/components");
    expect(page).toContain(":::caution[Heads up]");
    expect(page).toContain('<Tab title="npm">');
    // Frontmatter folded onto Blume's shape.
    expect(page).toContain("exclude: true");
    expect(page).toContain("badge: New");
    expect(page).not.toContain("template: splash");
  });
});

describe("starlight unit mappers", () => {
  it("maps a per-page sidebar badge object to a string", () => {
    const { data, removed } = normalizeStarlightPageMeta({
      pagefind: false,
      sidebar: { badge: { text: "New", variant: "tip" } },
      template: "splash",
      title: "Page",
    });
    expect((data.sidebar as { badge?: string }).badge).toBe("New");
    expect((data.search as { exclude?: boolean }).exclude).toBe(true);
    expect(removed).toContain("template");
  });

  it("converts <Aside> JSX to directives and renames containers", () => {
    expect(rewriteStarlightAsides("<Aside type='tip'>ok</Aside>")).toContain(
      ":::tip"
    );
    const out = rewriteStarlightComponents(
      '<CardGrid><LinkCard title="A" href="/a" /></CardGrid>'
    );
    expect(out).toContain("<CardGroup>");
    expect(out).toContain("<Card ");
    expect(
      stripStarlightImports(
        'import x from "@astrojs/starlight/components";\n# Hi'
      )
    ).toBe("# Hi");
    expect(unsupportedStarlightComponents("<Steps>\n1. a\n</Steps>")).toContain(
      "Steps"
    );
  });

  it("maps title and sidebar groups without an astro config eval", () => {
    const config = mapStarlightConfig(
      {
        sidebar: [{ autogenerate: { directory: "reference" }, label: "Ref" }],
        title: "T",
      },
      []
    );
    expect(config.title).toBe("T");
    expect(config.content).toEqual({ root: "src/content/docs" });
    expect(config.navigation?.sidebar).toEqual([
      { label: "Ref", root: "reference" },
    ]);
    expect(blumeConfigSchema.safeParse(config).success).toBe(true);
  });

  it("maps Starlight locales onto an i18n config", () => {
    const i18n = starlightI18n({
      defaultLocale: "en",
      locales: {
        fr: { label: "Français", lang: "fr" },
        root: { label: "English", lang: "en" },
      },
    });
    expect(i18n?.defaultLocale).toBe("en");
    expect(i18n?.parser).toBe("dir");
    expect(i18n?.locales).toContainEqual({ code: "fr", label: "Français" });
  });
});
